### ISSUE TITLE
Docker implementation

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-foundation#20]
We should try to use Docker for managing all of this stuff.

**Comment by ForNeVeR** [comment]
No we shouldn't.

**Comment by ForNeVeR** [comment]
I've changed my mind. We still should try.

**Comment by rexim** [comment]
~___~

**Comment by ForNeVeR** [comment]
WHAT? .\ _ /.

**Comment by rexim** [comment]
Who are you talking to?

**Comment by ForNeVeR** [comment]
I am talking to you, little mixer.
