### ISSUE TITLE
Chef provisioning

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/horta-foundation#22]
I think that project should use [Chef](https://www.chef.io/) for provisioning instead of that ugly shell scripts.

**Comment by rexim** [comment]
You suggests to use some ugly svg logo instead of ugly shell scripts?

**Comment by ForNeVeR** [comment]
Anything would be better than `bash` - even SVG.

(And regarding the real issue - thanks, I've fixed the link.)

**Comment by rexim** [comment]
Yeah, thanks. Very interesting thing... Have you used it already somewhere?

**Comment by ForNeVeR** [comment]
I've used it for provision of a virtual machine for building [Frege](https://github.com/Frege/frege). I've also tried another automating solutions such as Puppet and Docker and I like Chef more.
